<?php

namespace Acme\ApiBundle\Repository;

/**
 * TrucRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrucRepository extends \Doctrine\ORM\EntityRepository
{
}
